# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f096db1af0293fff92c2dd2f10d7c24e1f6bca53f9a0065554ad97cc05a77dccb47c34c387ef480905ec9d7c145e45b62b321bc90b94dce92cf7c7618cb0a9ac

test:
  secret_key_base: 637704b2fb0dbb28e398ceba29b6a67550ef866775750b6bc9a991cee4cbc75796f0f6a903a3aac16e432b254ed44bf31f04add8daf471f789f87df08b337532

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
